export interface AppWork {
  id: string
  titleKey: string
  descriptionKey: string
  description2Key?: string
  image: string
  url?: string
}

export const APP_WORKS: AppWork[] = [
  {
    id: 'wealthy-01',
    titleKey: 'wealthy.title',
    descriptionKey: 'wealthy01.description',
    description2Key: 'wealthy01.description2',
    image: '/apps/wealthy-01.png',
    url: 'https://itunes.apple.com/app/wealthy!-track-expenses-take/id714626591',
  },
  {
    id: 'wealthy-02',
    titleKey: 'wealthy.title',
    descriptionKey: 'wealthy02.description',
    description2Key: 'wealthy02.description2',
    image: '/apps/wealthy-02.png',
    url: 'https://itunes.apple.com/app/wealthy!-track-expenses-take/id714626591',
  },
  {
    id: 'wealthy-03',
    titleKey: 'wealthy.title',
    descriptionKey: 'wealthy03.description',
    description2Key: 'wealthy03.description2',
    image: '/apps/wealthy-03.png',
    url: 'https://itunes.apple.com/app/wealthy!-track-expenses-take/id714626591',
  },
  {
    id: 'wealthy-04',
    titleKey: 'wealthy.title',
    descriptionKey: 'wealthy04.description',
    image: '/apps/wealthy-04.png',
    url: 'https://itunes.apple.com/app/wealthy!-track-expenses-take/id714626591',
  },
  {
    id: 'penny-home-01',
    titleKey: 'pennyHome.title',
    descriptionKey: 'pennyHome01.description',
    description2Key: 'pennyHome01.description2',
    image: '/apps/penny-home-01.png',
  },
  {
    id: 'penny-home-02',
    titleKey: 'pennyHome.title',
    descriptionKey: 'pennyHome02.description',
    description2Key: 'pennyHome02.description2',
    image: '/apps/penny-home-02.png',
  },
  {
    id: 'penny-home-03',
    titleKey: 'pennyHome.title',
    descriptionKey: 'pennyHome03.description',
    description2Key: 'pennyHome03.description2',
    image: '/apps/penny-home-03.png',
  },
  {
    id: 'penny-home-04',
    titleKey: 'pennyHome.title',
    descriptionKey: 'pennyHome04.description',
    description2Key: 'pennyHome04.description2',
    image: '/apps/penny-home-04.png',
  },
  {
    id: 'apart-01',
    titleKey: 'apart.title',
    descriptionKey: 'apart01.description',
    description2Key: 'apart01.description2',
    image: '/apps/apart-01.png',
    url: 'https://itunes.apple.com/app/apart-group-socializing/id977933667',
  },
  {
    id: 'apart-02',
    titleKey: 'apart.title',
    descriptionKey: 'apart02.description',
    image: '/apps/apart-02.png',
    url: 'https://itunes.apple.com/app/apart-group-socializing/id977933667',
  },
  {
    id: 'apart-03',
    titleKey: 'apart.title',
    descriptionKey: 'apart03.description',
    image: '/apps/apart-03.png',
    url: 'https://itunes.apple.com/app/apart-group-socializing/id977933667',
  },
  {
    id: 'apart-04',
    titleKey: 'apart.title',
    descriptionKey: 'apart04.description',
    image: '/apps/apart-04.png',
    url: 'https://itunes.apple.com/app/apart-group-socializing/id977933667',
  },
  {
    id: 'acaia-01',
    titleKey: 'acaia.title',
    descriptionKey: 'acaia01.description',
    description2Key: 'acaia01.description2',
    image: '/apps/acaia-01.png',
    url: 'https://itunes.apple.com/app/acaia-coffee/id834883045',
  },
  {
    id: 'acaia-02',
    titleKey: 'acaia.title',
    descriptionKey: 'acaia02.description',
    description2Key: 'acaia02.description2',
    image: '/apps/acaia-02.png',
    url: 'https://itunes.apple.com/app/acaia-coffee/id834883045',
  },
  {
    id: 'acaia-03',
    titleKey: 'acaia.title',
    descriptionKey: 'acaia03.description',
    description2Key: 'acaia03.description2',
    image: '/apps/acaia-03.png',
    url: 'https://itunes.apple.com/app/acaia-coffee/id834883045',
  },
  {
    id: 'acaia-04',
    titleKey: 'acaia.title',
    descriptionKey: 'acaia04.description',
    description2Key: 'acaia04.description2',
    image: '/apps/acaia-04.png',
    url: 'https://itunes.apple.com/app/acaia-coffee/id834883045',
  },
  {
    id: 'vk-01',
    titleKey: 'vk.title',
    descriptionKey: 'vk01.description',
    description2Key: 'vk01.description2',
    image: '/apps/vk-01.png',
  },
  {
    id: 'vk-02',
    titleKey: 'vk.title',
    descriptionKey: 'vk02.description',
    image: '/apps/vk-02.png',
  },
  {
    id: 'vk-03',
    titleKey: 'vk.title',
    descriptionKey: 'vk03.description',
    image: '/apps/vk-03.png',
  },
  {
    id: 'vk-04',
    titleKey: 'vk.title',
    descriptionKey: 'vk04.description',
    image: '/apps/vk-04.png',
  },
  {
    id: 'minihana-01',
    titleKey: 'minihana.title',
    descriptionKey: 'minihana01.description',
    description2Key: 'minihana01.description2',
    image: '/apps/minihana-01.png',
  },
  {
    id: 'minihana-02',
    titleKey: 'minihana.title',
    descriptionKey: 'minihana02.description',
    image: '/apps/minihana-02.png',
  },
  {
    id: 'minihana-03',
    titleKey: 'minihana.title',
    descriptionKey: 'minihana03.description',
    image: '/apps/minihana-03.png',
  },
  {
    id: 'minihana-04',
    titleKey: 'minihana.title',
    descriptionKey: 'minihana04.description',
    image: '/apps/minihana-04.png',
  },
  {
    id: 'locomo-01',
    titleKey: 'locomo.title',
    descriptionKey: 'locomo01.description',
    description2Key: 'locomo01.description2',
    image: '/apps/locomo-01.png',
    url: 'https://itunes.apple.com/app/locomo-yun-dong-ji-lu/id537144570',
  },
  {
    id: 'locomo-02',
    titleKey: 'locomo.title',
    descriptionKey: 'locomo02.description',
    description2Key: 'locomo02.description2',
    image: '/apps/locomo-02.png',
    url: 'https://itunes.apple.com/app/locomo-yun-dong-ji-lu/id537144570',
  },
  {
    id: 'locomo-03',
    titleKey: 'locomo.title',
    descriptionKey: 'locomo03.description',
    description2Key: 'locomo03.description2',
    image: '/apps/locomo-03.png',
    url: 'https://itunes.apple.com/app/locomo-yun-dong-ji-lu/id537144570',
  },
  {
    id: 'locomo-04',
    titleKey: 'locomo.title',
    descriptionKey: 'locomo04.description',
    image: '/apps/locomo-04.png',
    url: 'https://itunes.apple.com/app/locomo-yun-dong-ji-lu/id537144570',
  },
  {
    id: 'fitmi-01',
    titleKey: 'fitmi.title',
    descriptionKey: 'fitmi01.description',
    description2Key: 'fitmi01.description2',
    image: '/apps/fitmi-01.png',
  },
  {
    id: 'fitmi-02',
    titleKey: 'fitmi.title',
    descriptionKey: 'fitmi02.description',
    image: '/apps/fitmi-02.png',
  },
  {
    id: 'fitmi-03',
    titleKey: 'fitmi.title',
    descriptionKey: 'fitmi03.description',
    image: '/apps/fitmi-03.png',
  },
  {
    id: 'fitmi-04',
    titleKey: 'fitmi.title',
    descriptionKey: 'fitmi04.description',
    image: '/apps/fitmi-04.png',
  },
  {
    id: 'toeic-01',
    titleKey: 'toeic.title',
    descriptionKey: 'toeic01.description',
    description2Key: 'toeic01.description2',
    image: '/apps/toeic-01.png',
  },
  {
    id: 'toeic-02',
    titleKey: 'toeic.title',
    descriptionKey: 'toeic02.description',
    image: '/apps/toeic-02.png',
  },
  {
    id: 'toeic-03',
    titleKey: 'toeic.title',
    descriptionKey: 'toeic03.description',
    image: '/apps/toeic-03.png',
  },
  {
    id: 'toeic-04',
    titleKey: 'toeic.title',
    descriptionKey: 'toeic04.description',
    image: '/apps/toeic-04.png',
  },
  {
    id: 'super-singer-01',
    titleKey: 'superSinger.title',
    descriptionKey: 'superSinger01.description',
    image: '/apps/super-singer-01.png',
  },
  {
    id: 'super-singer-02',
    titleKey: 'superSinger.title',
    descriptionKey: 'superSinger02.description',
    image: '/apps/super-singer-02.png',
  },
  {
    id: 'super-singer-03',
    titleKey: 'superSinger.title',
    descriptionKey: 'superSinger03.description',
    image: '/apps/super-singer-03.png',
  },
  {
    id: 'super-singer-04',
    titleKey: 'superSinger.title',
    descriptionKey: 'superSinger04.description',
    image: '/apps/super-singer-04.png',
  },
  {
    id: 'wretch-01',
    titleKey: 'wretch.title',
    descriptionKey: 'wretch01.description',
    image: '/apps/wretch-01.png',
  },
  {
    id: 'wretch-02',
    titleKey: 'wretch.title',
    descriptionKey: 'wretch02.description',
    image: '/apps/wretch-02.png',
  },
  {
    id: 'wretch-03',
    titleKey: 'wretch.title',
    descriptionKey: 'wretch03.description',
    image: '/apps/wretch-03.png',
  },
  {
    id: 'wretch-04',
    titleKey: 'wretch.title',
    descriptionKey: 'wretch04.description',
    image: '/apps/wretch-04.png',
  },
]
